<?php

namespace ContainerQqIyU5F;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateUserService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\CreateUser' shared autowired service.
     *
     * @return \App\Controller\CreateUser
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/CreateUser.php';

        $container->services['App\\Controller\\CreateUser'] = $instance = new \App\Controller\CreateUser();

        $instance->setContainer(($container->privates['.service_locator.g9CqTPp'] ?? $container->load('get_ServiceLocator_G9CqTPpService'))->withContext('App\\Controller\\CreateUser', $container));

        return $instance;
    }
}
