<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQqIyU5F\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQqIyU5F/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQqIyU5F.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQqIyU5F\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQqIyU5F\App_KernelDevDebugContainer([
    'container.build_hash' => 'QqIyU5F',
    'container.build_id' => '407d8b42',
    'container.build_time' => 1593244266,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQqIyU5F');
